# Generated by Django 6.0.7 on 2026-08-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stocks',
            new_name='quantity',
        ),
    ]
